# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('SC', 'Smart Card'), ('EM', 'E-Money'), ('EFT', 'Electronic Fund Transfer'), ('COD', 'Cash On Delivery')], default='CC', max_length=10)),
                ('status', models.CharField(choices=[('NA', 'Not Approved'), ('A', 'Approved'), ('P', 'Packed'), ('S', 'Shipped'), ('D', 'Delivered')], default='NA', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
