# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(default='', max_length=32),
        ),
    ]
